resources:
  - deployment.yaml
  - service.yaml
  - storage/longhorn.pv.yaml
  - storage/nfs.pv.yaml
  - storage/pvc.yaml

namePrefix: opencloud-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: opencloud
  - pairs:
      needs-media: "true"
  
namespace: org

images:
- name: opencloud
  newName: opencloudeu/opencloud
  newTag: "2.0.5"
    
configMapGenerator:
  - name: map
    env: env/properties
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patches/node-affinity.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patches/security-context.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: config-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: config-pv
    fieldPaths:
    - spec.csi.volumeHandle
