apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: forgejo
        image: forgejo
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300Mi"
            cpu: "150m"
          limits:
            memory: "500Mi"
            cpu: "300m"
        ports:
        - name: web
          containerPort: 3000
        - name: ssh
          containerPort: 22
        envFrom:
        - configMapRef:
            name: map
        - secretRef:
            name: secret
        volumeMounts:
#        - name: config
#          mountPath: /etc/gitea
        - name: data
          mountPath: /data
        - name: timezone
          mountPath: /etc/timezone
          subPath: timezone
      volumes:
#      - name: config
#        persistentVolumeClaim:
#          claimName: config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: timezone
        configMap:
          name: map
          items:
          - key: timezone
            path: timezone
