resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage/longhorn.pv.yaml
  - storage/pvc.yaml

namePrefix: forgejo-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: forgejo
  
namespace: util

images:
- name: forgejo
  newName: codeberg.org/forgejo/forgejo
  newTag: "13.0.2"
    
configMapGenerator:
  - name: map
    env: env/properties
    files:
      - env/timezone
    
secretGenerator:
  - name: secret
    env: env/passwords
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
#  - target:
#      kind: Deployment
#      name: deployment
#    path: patches/security-context.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: data-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: data-pv
    fieldPaths:
    - spec.csi.volumeHandle
